version: '3.7'

services:
  postgres:
    image: postgres:12
    restart: always
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    hostname: redis
    ports:
      - '6379:6379'

  manager:
    image: ohbug/ohbug-ce:latest
    restart: always
    ports:
      - '8880:8880'
    env_file: .env.production
    entrypoint: ['node', './ohbug/manager/main.js']
    depends_on:
      - postgres
      - redis

  notifier:
    image: ohbug/ohbug-ce:latest
    restart: always
    ports:
      - '8881:8881'
    env_file: .env.production
    entrypoint: ['node', './ohbug/notifier/main.js']
    depends_on:
      - postgres
      - redis

  dashboard:
    image: ohbug/ohbug-ce:latest
    restart: always
    ports:
      - '6666:6666'
    env_file: .env.production
    entrypoint: ['node', './ohbug/dashboard/main.js']
    volumes:
      - /app/ohbug
    depends_on:
      - postgres
      - redis

  transfer:
    image: ohbug/ohbug-ce:latest
    restart: always
    ports:
      - '6660:6660'
    env_file: .env.production
    entrypoint: ['node', './ohbug/transfer/main.js']
    healthcheck:
      test: curl --max-time 60 --retry 60 --retry-delay 1 --retry-connrefused --show-error --silent http://localhost:6660
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
